name: Build and Release

on:
  push:
    branches:
      - saga

permissions:
  id-token: write
  contents: write
  issues: write
  pages: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Get current release
        run: echo "currentRelease=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Determine next release version
        uses: nordicsemiconductor/cloud-get-next-version-action@saga
        id: version
        with:
          branch: saga
          defaultVersion: "${{ env.currentRelease }}-${{ github.sha }}"

      - name: Build
        env:
          VERSION: ${{ steps.version.outputs.nextRelease }}
        run: |
          npm run build
          cp -v -L -r ./static ./build/client

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/client

  deploy:
    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

  # Seperate step so git is clean
  release:
    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Semantic release
        run: npx semantic-release
