name: UNCSS

on:
  push:
    branches:
      - gh-pages

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  uncss:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: npm ci --no-audit
      - name: Start local server
        run: docker run -d -it --rm -v "$PWD":/usr/src/app -p "4000:4000" starefossen/github-pages > /tmp/docker.pid
      - name: ensure the server is running
        run: for i in {1..30}; do curl http://127.0.0.1:4000/23/dev.html && break || sleep 1; done
      - name: UNCSS
        run: npx uncss http://127.0.0.1:4000/23/dev.html > 23/theme.uncss.css
      - name: Commit build
        run: |
          echo "machine github.com login coderbyheart password ${GITHUB_TOKEN}" > ~/.netrc
          git config user.email "actions@example.com"
          git config user.name "GitHub Actions"
          git status
          CHANGED=$(git diff-index --name-only HEAD -- 23/theme.uncss.css)
          if [ -n "$CHANGED" ]; then
              git add 23/theme.uncss.css
              git commit -m "build: update CSS build"
              git push origin HEAD:gh-pages
          fi
      - name: Logs
        if: always()
        run: docker logs `cat /tmp/docker.pid`
      - name: Stop local server
        if: always()
        run: docker stop `cat /tmp/docker.pid`
